// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QI.Infrastructure;

#nullable disable

namespace qiapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("qiapi.Models.AuthCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuthCredential");
                });

            modelBuilder.Entity("qiapi.Models.Heartbeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emotion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Intensity")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SignalId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SignalId");

                    b.HasIndex("UserId");

                    b.ToTable("Heartbeats");
                });

            modelBuilder.Entity("qiapi.Models.Insight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resonance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TriggeredBySignalId")
                        .HasColumnType("int");

                    b.Property<string>("Unlocked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredBySignalId");

                    b.HasIndex("UserId");

                    b.ToTable("Insights");
                });

            modelBuilder.Entity("qiapi.Models.Mirror", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LinkedHeartbeatId")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedInsightId")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedWhisperId")
                        .HasColumnType("int");

                    b.Property<string>("MirrorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReflectedFromUserId")
                        .HasColumnType("int");

                    b.Property<string>("Transparency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruthResonanceScore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LinkedHeartbeatId");

                    b.HasIndex("LinkedInsightId");

                    b.HasIndex("LinkedWhisperId");

                    b.HasIndex("ReflectedFromUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Mirrors");
                });

            modelBuilder.Entity("qiapi.Models.Signal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resonance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Signals");
                });

            modelBuilder.Entity("qiapi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FrequencyLevel")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoulRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoulSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("qiapi.Models.Whisper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClarityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeltResonance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LinkedHeartbeatId")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedSignalId")
                        .HasColumnType("int");

                    b.Property<string>("NoticedBecause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointingTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResultedInsightId")
                        .HasColumnType("int");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LinkedHeartbeatId");

                    b.HasIndex("LinkedSignalId");

                    b.HasIndex("ResultedInsightId");

                    b.HasIndex("UserId");

                    b.ToTable("Whispers");
                });

            modelBuilder.Entity("qiapi.Models.Heartbeat", b =>
                {
                    b.HasOne("qiapi.Models.Signal", "Signal")
                        .WithMany("RelatedHeartbeats")
                        .HasForeignKey("SignalId");

                    b.HasOne("qiapi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("qiapi.Models.Insight", b =>
                {
                    b.HasOne("qiapi.Models.Signal", "TriggeredBySignal")
                        .WithMany()
                        .HasForeignKey("TriggeredBySignalId");

                    b.HasOne("qiapi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriggeredBySignal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("qiapi.Models.Mirror", b =>
                {
                    b.HasOne("qiapi.Models.Heartbeat", "LinkedHeartbeat")
                        .WithMany()
                        .HasForeignKey("LinkedHeartbeatId");

                    b.HasOne("qiapi.Models.Insight", "LinkedInsight")
                        .WithMany()
                        .HasForeignKey("LinkedInsightId");

                    b.HasOne("qiapi.Models.Whisper", "LinkedWhisper")
                        .WithMany()
                        .HasForeignKey("LinkedWhisperId");

                    b.HasOne("qiapi.Models.User", "ReflectedFromUser")
                        .WithMany()
                        .HasForeignKey("ReflectedFromUserId");

                    b.HasOne("qiapi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedHeartbeat");

                    b.Navigation("LinkedInsight");

                    b.Navigation("LinkedWhisper");

                    b.Navigation("ReflectedFromUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("qiapi.Models.Signal", b =>
                {
                    b.HasOne("qiapi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("qiapi.Models.Whisper", b =>
                {
                    b.HasOne("qiapi.Models.Heartbeat", "LinkedHeartbeat")
                        .WithMany()
                        .HasForeignKey("LinkedHeartbeatId");

                    b.HasOne("qiapi.Models.Signal", "LinkedSignal")
                        .WithMany()
                        .HasForeignKey("LinkedSignalId");

                    b.HasOne("qiapi.Models.Insight", "ResultedInsight")
                        .WithMany()
                        .HasForeignKey("ResultedInsightId");

                    b.HasOne("qiapi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedHeartbeat");

                    b.Navigation("LinkedSignal");

                    b.Navigation("ResultedInsight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("qiapi.Models.Signal", b =>
                {
                    b.Navigation("RelatedHeartbeats");
                });
#pragma warning restore 612, 618
        }
    }
}
